"""empty message

Revision ID: 223c08573099
Revises: 3d5bf149b1d3
Create Date: 2015-04-28 15:03:47.864325

"""

# revision identifiers, used by Alembic.
revision = '223c08573099'
down_revision = '3d5bf149b1d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
