"""empty message

Revision ID: 260451d35c8b
Revises: 365073c8f3d9
Create Date: 2015-04-29 16:00:06.139056

"""

# revision identifiers, used by Alembic.
revision = '260451d35c8b'
down_revision = '365073c8f3d9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.add_column('answer', sa.Column('votes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'votes')
    op.create_table('vote',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], [u'answer.id'], name=u'vote_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'vote_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
