"""empty message

Revision ID: 2c0cb16b3e21
Revises: 55d95efa4193
Create Date: 2015-04-29 09:41:09.000448

"""

# revision identifiers, used by Alembic.
revision = '2c0cb16b3e21'
down_revision = '55d95efa4193'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
