"""empty message

Revision ID: 365073c8f3d9
Revises: 3feea0554ec
Create Date: 2015-04-29 14:48:33.841638

"""

# revision identifiers, used by Alembic.
revision = '365073c8f3d9'
down_revision = '3feea0554ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
