"""empty message

Revision ID: 55d95efa4193
Revises: 223c08573099
Create Date: 2015-04-28 17:41:44.883681

"""

# revision identifiers, used by Alembic.
revision = '55d95efa4193'
down_revision = '223c08573099'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
