"""empty message

Revision ID: ab9187cba15
Revises: 2c0cb16b3e21
Create Date: 2015-04-29 10:54:50.087705

"""

# revision identifiers, used by Alembic.
revision = 'ab9187cba15'
down_revision = '2c0cb16b3e21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    ### end Alembic commands ###
